# Generated by Django 6.1 on 2026-09-04 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='kategoriya',
            field=models.CharField(choices=[('texnologiya', 'Texnologiya'), ('hayot', 'Hayot'), ('sport', 'Sport')], default='texnologiya', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='korildi',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='nashr_etilgan',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='yangilangan_sana',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Izoh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('matn', models.TextField()),
                ('yaratilgan_sana', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='izohlar', to='blog.post')),
            ],
        ),
    ]
