# Generated by Django 6.1 on 2026-09-07 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_legacy_authors(apps, schema_editor):
    Post = apps.get_model('blog', 'Post')
    User = apps.get_model('auth', 'User')

    legacy_authors = Post.objects.values_list('muallif', flat=True).distinct()
    for author_name in legacy_authors:
        user, _ = User.objects.get_or_create(
            username=author_name,
            defaults={
                'first_name': author_name,
            },
        )
        Post.objects.filter(muallif=author_name).update(muallif=user.pk)


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_kategoriya_post_korildi_post_nashr_etilgan_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rasm',
            field=models.ImageField(blank=True, null=True, upload_to='postlar/'),
        ),
        migrations.RunPython(migrate_legacy_authors, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='post',
            name='muallif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
